SOURCES/xenopsd-32a56a1a800fe9d1e917a986734baac695776152
SPECS/xenopsd.spec

Signed-off-by: David Scott <dave.scott@eu.citrix.com>

Backport xenopsd libxl workaround

---

SPECS/ocaml-ocplib-endian.spec

ocaml-ocplib-endian: Update to v0.8

---

scripts/deb/configure.sh

deb/configure: Refactor package installation

---

SOURCES/xenopsd-e925eb7b92c6874bdf359c3091a3e02cb288baa0.patch
SPECS/xenopsd.spec

Signed-off-by: David Scott <dave.scott@eu.citrix.com>

xenopsd: backport blkback fix

---

SOURCES/blktap-priu64.patch
SPECS/blktap.spec

Signed-off-by: David Scott <dave.scott@eu.citrix.com>

blktap: fix build on 32-bit machines

---

SPECS/ezlvm.spec

Update ezlvm to 0.4

---

SPECS/ezlvm.spec

This avoids compiling them on the target machine.

ezlvm: compile the scripts

---

SPECS/xcp-networkd.spec

Signed-off-by: David Scott <dave.scott@eu.citrix.com>

Update xcp-networkd to latest version

---

SPECS/ocaml-xcp-idl.spec
SPECS/vhd-tool.spec
SPECS/xapi-quicktest.spec

ocaml-xcp-idl, vhd-tool, xapi-quicktest: Fix bogus changelog dates

---

SPECS/ocaml-camldm.spec
SPECS/ocaml-ctypes.spec
SPECS/ocaml-kaputt.spec
SPECS/ocaml-lwt.spec
SPECS/ocaml-mirage-block-unix.spec
SPECS/ocaml-mirage-block-volume.spec
SPECS/ocaml-netlink.spec
SPECS/ocaml-shared-block-ring.spec
SPECS/xenvm.spec

Rebased thin-lvhd

---

SPECS/ocaml-inotify.spec

inotify: Fix Source0 to give a well-formed tarball name

---

SPECS/ocaml-cmdliner.spec

ocaml-cmdliner: Switch back to GitHub mirror

---

scripts/deb/configure.sh

Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

deb/configure.sh: allow out-of-band installation of planex

---

SPECS/forkexecd.spec
SPECS/ocaml-netdev.spec
SPECS/ocaml-rrd-transport.spec
SPECS/ocaml-rrdd-plugin.spec
SPECS/ocaml-stdext.spec
SPECS/ocaml-tapctl.spec
SPECS/ocaml-xcp-inventory.spec
SPECS/ocaml-xcp-rrd.spec
SPECS/ocaml-xen-api-client.spec
SPECS/ocaml-xen-api-libs-transitional.spec
SPECS/ocaml-xenops.spec
SPECS/squeezed.spec
SPECS/vhd-tool.spec
SPECS/xcp-networkd.spec
SPECS/xenops-cli.spec

Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

Bump many specs for copr rebuild

---

SOURCES/xcp-rrdd-init
SOURCES/xen-api-xapi-conf.in
SPECS/ffs.spec
SPECS/xapi.spec
SPECS/xcp-rrdd.spec

This is fallout from
- change in argument parsing code
- change in queue names ('xcp' -> 'xapi')

Minor init script, config file updates

---

SPECS/ffs.spec

ffs: install library files into the 'ffs' package

---

SPECS/xenserver-install-wizard.spec

Update to xenserver-install-wizard 0.2.40

---

SPECS/xenserver-install-wizard.spec

Bump xenserver-install-wizard to 0.2.41

---

SPECS/ffs.spec

Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

Bump the release of ffs

---

SPECS/ocaml-vhd.spec
SPECS/vhd-tool.spec

Update ocaml-vhd and vhd-tool

---

SPECS/ffs.spec
SPECS/xapi-storage-datapath-plugins.spec
SPECS/xapi-storage.spec
SPECS/xenserver-core.spec

Update to the new ffs package layout

---

SPECS/ocamlscript.spec

Update ocamlscript to 2.0.4

---

SPECS/ezlvm.spec
SPECS/xenserver-core.spec

Re-add ezlvm

---

SPECS/ezlvm.spec

Update ezlvm to 0.5.1

---

SPECS/xapi-storage-script.spec

Bump spec of xapi-storage-script

---

SPECS/ezlvm.spec
SPECS/xapi-storage-script.spec
SPECS/xapi-storage.spec

xapi-storage: package other python files

---

SPECS/xapi-storage-datapath-plugins.spec

Update xapi-storage-datapath-plugins to 0.2.1

---

SPECS/ezlvm.spec

Update ezlvm to 0.5.2

---

SPECS/ezlvm.spec

Update ezlvm to 0.5.3

---

SPECS/busybox.spec
SPECS/xenserver-core.spec

Signed-off-by: Jon Ludlam <jonathan.ludlam@citrix.com>

Add busybox

---

SPECS/ocaml-qmp.spec

Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

ocaml-qmp: Update to 0.9.3
